version: '3'
services:
  MosaicPipeline-cpu:
    hostname: '$host'
    user: "${UID}:${GID}"
    image: mosaic-image-cpu
    environment:
      - CTX_ID=-1
      - PYTHONUNBUFFERED=1
    build:
      context: ./
      dockerfile: Dockerfile-cpu
    command:
      python run.py
    volumes:
      - ./src:/src
      - $CONFIG_PATH:/external_config.yaml
      - $DATASETS_PATH:/Dataset
      - $MODELS_PATH:/.insightface/models/
      - $RESULTS_PATH/Exp1-Mosaic:/Results
    container_name: mosaic-container-cpu
  MosaicPipeline-gpu:
    hostname: '$host'
    user: "${UID}:${GID}"
    image: mosaic-image-gpu
    #runtime: nvidia
    environment:
      - CTX_ID=1
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONUNBUFFERED=1
    build:
      context: ./
      dockerfile: Dockerfile-gpu
    command:
      python -u run.py
    volumes:
      - ./src:/src
      - $CONFIG_PATH:/external_config.yaml
      - $DATASETS_PATH:/Dataset
      - $MODELS_PATH:/root/.insightface/models/
      - $RESULTS_PATH/Exp1-Mosaic:/Results
    container_name: mosaic-container-gpu
