version: '3'
services:
  MosaicPipeline-cpu:
    hostname: '$host'
    image: mosaic-image-cpu
    environment:
      - CTX_ID=-1
      - PYTHONUNBUFFERED=1
    build:
      context: ./
      dockerfile: Dockerfile-cpu
    command:
      python run.py
    volumes:
      - ./src:/src
      - ./Dataset:/Dataset
      - ./Models:/root/.insightface/models/
      - ./Results:/Results
    container_name: mosaic-container-cpu
  MosaicPipeline-gpu:
    hostname: '$host'
    image: mosaic-image-gpu
    runtime: nvidia
    environment:
      - CTX_ID=1
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONUNBUFFERED=1
    build:
      context: ./
      dockerfile: Dockerfile-gpu
    command:
      python -u run.py
    volumes:
      - ./src:/src
      - ./Dataset:/Dataset
      - ./Models:/root/.insightface/models/
      - ./Results:/Results
    container_name: mosaic-container-gpu
