# ====== STRING ====== #
output: Pipeline_Output # Name to identify the output
input_dataset: Dataset # Name of the input dataset directory (it must be under the )
output_extension: .jpg # Extension for the output images (.jpg, .png, .bmp ...)
log_level: INFO # Log level. Options: DEBUG, INFO, WARNING, ERROR, CRITICAL

# ====== INTEGER ====== #
bbox_size: 68 # BBox resolution (Always square: nxn)
dot_size: 3 # Size for the dot that will be printed on the image (partial results only)
det_size: 640 # Detection kernel size

# ====== FLOAT ====== #
mosaic_alpha: 0.4 # alpha [0-1]

# ====== BOOLEAN ====== #
partial_results: True # Store the partial results
show_numbers: False # When printing dots also print the corresponding numbers
process_detection: True # Process the detection step
process_mosaic: True # Process the mosaic step